# rabbitmq configuration
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# loading the csv files    
csv:
  files:
    - Employee.csv
    - SalesInfo.csv
    - Student.csv
    
# Logging properties.
logging:
  file:
     # Log file path.
     path: /opt/app/log/
    